# Generated by Django 5.0.3 on 2024-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('age', models.CharField(max_length=2)),
                ('email', models.CharField(default='', max_length=64)),
                ('origination_city', models.CharField(max_length=64)),
                ('origination_state', models.CharField(max_length=64)),
                ('destination_city', models.CharField(max_length=64)),
                ('destination_state', models.CharField(max_length=2)),
                ('vehicle_make', models.CharField(default='', max_length=64)),
                ('vehicle_model', models.CharField(default='', max_length=64)),
                ('vehicle_color', models.CharField(default='', max_length=64)),
                ('is_regular', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taking_passengers', models.BooleanField(default=False)),
                ('seats_available', models.IntegerField(default=0)),
            ],
        ),
    ]
