# Generated by Django 5.0.3 on 2024-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.CharField(default='', max_length=64),
        ),
    ]
